
logging.level. = ERROR
logging.level.org.springframework.: ERROR

org.slf4j.simpleLogger.defaultLogLevel = info
org.slf4j.simpleLogger.log.gfs = debug

# logging.level.org.springframework=TRACE
# logging.level.com=TRACE

logging.level.org.springframework=INFO
logging.level.com=INFO

server.error.whitelabel.enabled=false
server.error.path=/error

logging.level.gfs. = INFO
logging.level.gfs.common. = INFO

# =====================
# APP
# =====================
appId=0
appName=Labber app
appDescription=Labber bootstrap app
appContext=/llm/
appResContext=/llm/res/
appAssetsContext=/llm/assets/
propertyFile=APP
# cacheMaxAge=12
# timeUnit=HOURS

# =====================
# SPRING
# =====================
server.contextPath=/llm
server.servlet.context-path=/llm
# spring.mvc.view.prefix=/
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# logging.level.org=INFO
# logging.level.org=INFO
# logging.level.com=INFO
# logging.level.root = INFO
# logging.level.org.apache.tomcat.util.net.NioEndpoint=INFO
# logging.level.org.springframework=TRACE

# =====================
# VAULT
# =====================

# =====================
# OAUTH
# =====================

# =====================
# GREMLIN
# =====================

# Gremlin 

# gremlin.url=10.88.88.112:8182
# gremlin.url=10.10.10.112:8182
# gremlin.url=192.168.1.112:8182
# gremlin.url=10.147.20.118:8182
# gremlin.url=10.88.88.156:8182
gremlin.url=10.88.88.60:8182
gremlin.username=root
gremlin.password=root

# =====================
# RABBIT
# =====================

# RabbitMQ

rabbitmq.url=
rabbitmq.username=
rabbitmq.password=

# =====================
# SPRING AI
# =====================

# spring.ai.chroma.uri=http://localhost:8000
# spring.ai.chroma.collection-name=my_collection

spring.ai.ollama.base-url=http://10.88.88.180:11434
spring.ai.ollama.chat.options.model=gpt-oss
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=nomic-embed-text

app.resource=classpath:docs/CDOC-119hdoc1.pdf
app.resource.vector-store.path=/tmp/rag-vectorstore.json

# ??
spring.liquibase.enabled=false

# =====================
# POSTGRES SQL PGVECTOR
# =====================
 
spring.datasource.url=jdbc:postgresql://10.88.88.197:5432/pgvector_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# spring.ai.ollama.embedding.options.dimensions=1024
# spring.ai.ollama.embedding.options.model=nomic-embed-text 

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# spring.ai.vectorstore.pgvector.dimension=1024
# spring.ai.vectorstore.pgvector.dimension=768
spring.ai.vectorstore.pgvector.dimension=1024
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=false
spring.ai.vectorstore.pgvector.schema-name=public
# spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.table-name=vector_store

# spring.ai.ollama.embedding.options.dimensions=1024
spring.ai.ollama.embedding.options.model=nomic-embed-text 
# spring.ai.ollama.embedding.options.model=nomic-embed-text-v2-moe
# spring.ai.ollama.embedding.options.model=mxbai-embed-large
